### ISSUE TITLE
ESP32 Access Point wiring

### ISSUE THREAD

**Issue by probonopd** [atc1441/E-Paper_Pricetags#17]
> Connect the CC1101 868 MHz radio module to the ESP32 using the pinout specified in the RFV3.h header file.

https://github.com/atc1441/E-Paper_Pricetags/blob/78a44580edc0f980931f94b63ca98ce65c26ddf2/Custom_PriceTag_AccesPoint/ESP32_Async_PlatformIO/RFV3/RFV3.h#L22-L28

Does this mean one should connect the yellow and the grey wire **both to the same pin** on the ESP32?

![image](https://user-images.githubusercontent.com/2480569/114320188-1abacb80-9b15-11eb-9821-46015a79c571.png)

[Graphic source](https://github.com/LSatan/SmartRC-CC1101-Driver-Lib/blob/master/img/Wiring_CC1101.png)

**Comment by atc1441** [comment]
Ah sorry, the GDO0 pin is currently not used, so you can leave it unconnected. 

it will maybe be used in the future but not for now

**Comment by probonopd** [comment]
Thank you.
Will watch **https://www.youtube.com/watch?v=pRoFim3Egss**, probably everything is explained there :+1:
