### ISSUE TITLE
Do not hardcode the WLAN credentials

### ISSUE THREAD

**Issue by probonopd** [atc1441/E-Paper_Pricetags#20]
Let's not hardcode the WLAN credentials. 

Using WiFiManager the device opens a temporary WLAN access point that can be used to tell the device which WLAN to connect to, and using which password.

![image](https://user-images.githubusercontent.com/2480569/114603221-c4c26100-9c97-11eb-8da8-d4ca20438eeb.png)

[Screenshot source](http://www.martyncurrey.com/esp8266-and-the-arduino-ide-part-5-adding-wifimanager/)

I have started to integrate this but since I am still waiting on devices I could not test this on hardware yet:

https://github.com/atc1441/E-Paper_Pricetags/compare/main...probonopd:patch-1

**Comment by atc1441** [comment]
Used it before with other projects and quite satisfied with it.

For simplicity i left hard coded credentials in development of the RF protocol in but got no problem with implementing it, also the usual OTA is still needed to be implemented :)

**Comment by probonopd** [comment]
Closed by https://github.com/atc1441/E-Paper_Pricetags/pull/21
