### ISSUE TITLE
Build using native Arduino toolkit fails

### ISSUE THREAD

**Issue by jruys** [atc1441/E-Paper_Pricetags#24]
Haven't had time to dive into this, opening just in case others run into this. Build using native Arduino toolkit started to fail after WifiManager merge.

Installed the library from https://github.com/tzapu/WiFiManager (not via native library manager)

Build exits with "'class WiFiClass' has no member named 'mode'"
Compile errors start with "error: redeclaration of 'HTTP_DELETE'   XX(0,  DELETE,      DELETE)"

Does WifiManager have version dependencies I may not have taken into consideration?

**Comment by atc1441** [comment]
Maybe this helps ? 
https://github.com/atc1441/E-Paper_Pricetags/blob/main/Custom_PriceTag_AccesPoint/ESP32_Async_PlatformIO/platformio.ini#L19

havent tested it myself in Arduino

**Comment by probonopd** [comment]
Yes, you definitely need to use the `feature_asyncwebserver` branch of https://github.com/tzapu/WiFiManager: https://github.com/tzapu/WiFiManager/archive/refs/heads/feature_asyncwebserver.zip

**Comment by jruys** [comment]
Confirmed: switching to that library fixes the issue. It now compiles ok.

**Comment by probonopd** [comment]
Sent a pull request to clarify the instructions. Thanks for pointing this out.
