### ISSUE TITLE
Always says "display: 0"

### ISSUE THREAD

**Issue by probonopd** [atc1441/E-Paper_Pricetags#29]
Always says "display: 0" in `answers.txt` and in the Status area.

https://github.com/atc1441/E-Paper_Pricetags/blob/e9588c02beff5b0430add6320040759919cb6710/Custom_PriceTag_AccesPoint/ESP32_Async_PlatformIO/RFV3/trans_assist.cpp#L118

**Comment by probonopd** [comment]
Looks like `set_display_id(id);` is _only_ ever called in `server.on("/set_custom", HTTP_POST, [](AsyncWebServerRequest *request)`, is that correct?

**Comment by atc1441** [comment]
The display id is used to send to the correct displays so is set correctly, my guess is that it is cleared to early so back 0

**Comment by atc1441** [comment]
The problem is here https://github.com/atc1441/E-Paper_Pricetags/blob/e9588c02beff5b0430add6320040759919cb6710/Custom_PriceTag_AccesPoint/ESP32_Async_PlatformIO/RFV3/main_variables.cpp#L102

**Comment by atc1441** [comment]
If we put save receive buffer above this one it will work again https://github.com/atc1441/E-Paper_Pricetags/blob/e9588c02beff5b0430add6320040759919cb6710/Custom_PriceTag_AccesPoint/ESP32_Async_PlatformIO/RFV3/mode_trans.h#L25
