### ISSUE TITLE
Use more standard bit rate for RFV3

### ISSUE THREAD

**Issue by probonopd** [atc1441/E-Paper_Pricetags#31]
Is there a particular reason why `RFV3.ino` is using 500000?

If not, it might be preferable to use a more standard bit rate. 115200 is the highest one the Arduino 2.0 IDE offers.

**Comment by atc1441** [comment]
115200 is to slow to send debug msgs in radio transmission.

If these debug msgs are disabled 115200 is fine

**Comment by probonopd** [comment]
OK, let's use it as is then. Thanks
