### ISSUE TITLE
Getting WakeUp during activation / resync counter

### ISSUE THREAD

**Issue by xsrf** [atc1441/E-Paper_Pricetags#37]
Hey,
it sometimes switches into WakeUp mode during activation of the Chroma29 ESLs. I guess this is because you're switching to sync/idle mode during activation on the activation channel and `resync_start_counter` may just kick in and mess with the activation, switching to WakeUp.
I guess adding a check in `mode_idle.h` would help 
```c
    if (resync_start_counter >= get_rounds_to_resync() && !get_last_to_short()  && !get_trans_mode())
```
But I'm wondering if it wouldn't be better to put the resync counter into a global scope and make sure it only triggers a resync after it was in sync/idle mode for the required intervals and reset it completely whenever an other mode is active?

**Comment by atc1441** [comment]
Yes the counter should be better in main_variables and check for further states before going into wakeup mode

**Comment by xsrf** [comment]
Actually, checking additional states wouldn't be required if modes other than sync+idle would just reset the counter.
